# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Bible' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bible
  pod 'AFNetworking', '~> 3.0' # 网络库
  pod 'WCDB.objc'               # 数据库框架
  pod 'Masonry'                # 布局框架
  pod 'LookinServer', :configurations => ['Debug'] # 布局排查工具
  target 'BibleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BibleUITests' do
    # Pods for testing
  end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end

end
